apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: rihofcg2q-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:f7528e92bdbeb76bb35784a2e790a1685752fda6@sha256:bc5abdd0fb124b8c645a6dba0b2e69394ca443ed7b484554d6fa58ccf119e147
          name: container-image
